FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y python3 python3-pip git cron

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y cron
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install transformers datasets peft bitsandbytes accelerate

CMD ["cron", "-f"]
